#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jun  4 12:19:05 2020

@author: aakarsh.rajagopalan
"""
"""
BERNOULLIS TRIAL
the purpose of this code is going to be to:
    1. identify the probability of getting heads in 10000 events.
"""
import numpy as np
import matplotlib.pyplot as plt

#seeding a number
np.random.seed(42)

#declaring a variable array to hold the random numbers generated by the random module
random_number = np.empty(10000)
#creating a for loop to simulate 10,000 events
for i in range(10000):
    random_number[i] = np.random.random()

_ = plt.hist(random_number)

_ = plt.xlabel('probability of head')
_ = plt.ylabel('number of times heads occurs')

_ = plt.show()
